services:
  - type: web
    name: stock-inventory-app
    env: node
    buildCommand: mkdir -p backend/build && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 